- name: Install aws-cli
  hosts: all
  become: yes
  remote_user: ubuntu
  become_user: root
  gather_facts: true

  vars_files:
    - vars.yml

  tasks:
    - name: Install aws-cli
      ansible.builtin.shell: |
        snap install aws-cli --classic

    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install nfs-common
      ansible.builtin.apt:
        pkg:
          - nfs-common

    - name: Mount file system
      ansible.builtin.shell: |
        mkdir -p /mnt/efs
        sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 {{ efs_id }}.efs.us-east-1.amazonaws.com:/ /mnt/efs
        chown -R 1000:1000 /mnt/efs

- name: Create docker registry ECR secret
  hosts: master
  remote_user: ubuntu
  gather_facts: false

  tasks:
    - name: Get ECR auth token
      shell: "aws ecr get-login-password --region us-east-1"
      register: ecr_auth_token_output

    - name: Set ecr_auth_token fact
      set_fact:
        ecr_auth_token: "{{ ecr_auth_token_output.stdout }}"

    - name: Show ecr_auth_token_output
      debug:
        msg: "{{ ecr_auth_token }}"

    - name: Update core dns configmap
      ansible.builtin.shell: |
        kubectl get configmap coredns -n kube-system -o yaml > dns-cf.yml
        sed -i 's|/etc/resolv\.conf|8.8.8.8|g' dns-cf.yml
        kubectl apply -f dns-cf.yml

    - name: Create ECR secret
      ansible.builtin.shell: |
        kubectl create namespace app-space
        kubectl create secret docker-registry ecr-creds \
        --docker-server=861936062471.dkr.ecr.us-east-1.amazonaws.com \
        --docker-username=AWS \
        --docker-password={{ ecr_auth_token }} \
        --namespace app-space

    - name: Install calico plugin
      ansible.builtin.shell: |
        kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml
